//try catch para poner ciertas lineas importantes del codigo y en caso de error, el codigo no deje de funcionar

const num1 = 20;
const num2 = 30;

console.log(num1);

try {
    console.log(num3);
} catch (error) {
    console.log(error)
}

console.log(num2);
